package salon.ai.engine.service;

import io.avaje.inject.External;
import jakarta.inject.Inject;
import jakarta.inject.Singleton;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import salon.ai.engine.internal.service.LowLevelAiService;
import salon.api.model.Client;
import salon.api.service.AiAssistantService;
import salon.api.service.BookingService;

/**
 * <h2>DESIGN INTENT: Clean Architecture Business Boundary Bridge</h2>
 * This component implements the public-facing {@link AiAssistantService} port contract interface
 * declared inside the {@code salon-api} module.
 *
 * <p><b>WHY IT EXISTS:</b>
 * Following the Dependency Inversion Principle (DIP), the web and API layers should never know
 * about the concrete AI frameworks we use. This class acts as a protective shield. It receives
 * standard Java types from the incoming webhook controllers, delegates the interaction to our internal
 * LangChain4j {@link LowLevelAiService} agent, and returns the response back to the caller.</p>
 *
 * <p><b>COMPILATION BOUNDARIES:</b>
 * This component is registered as an SPI extension service provider inside our {@code module-info.java}.
 * This allows the application to remain strictly modular: external consumers can inject and call the
 * {@code AiAssistantService} interface, but they have absolute zero compilation access to the internal
 * Jackson parsing engines, Ollama network links, or LangChain4j agent classes running under the hood.</p>
 */
@Singleton
final class AiAssistantServiceImpl implements AiAssistantService {

  private static final Logger log = LoggerFactory.getLogger(AiAssistantServiceImpl.class);

  private final BookingService bookingService;

  private final LowLevelAiService aiService;

  /**
   * Constructs the implementation adapter bridge.
   *
   * @param bookingService     The database-backed core use-case service port interface.
   *                           Marked with {@code @External} because it resides in a separate modular compilation
   *                           boundary graph, unblinding the factory compile processor.
   * @param lowLevelAiService  The compiled proxy implementation generated by the LangChain4j system factory.
   */
  @Inject
  AiAssistantServiceImpl(@External BookingService bookingService, LowLevelAiService aiService) {
    this.bookingService = bookingService;
    this.aiService = aiService;
  }

  @Override
  public String processChat(String telegramId, String userMessage) {
    log.info("Processing conversational routing trace context for user handle: {}", telegramId);

    final Client client = bookingService.identifyOrCreateTelegramClient(telegramId, "Valued Client");

    final String contextualPayload = String.format("[System Metadata Context: Client Database ID is %d. First Name: %s]\nUser Input: %s",
        client.id(), client.firstName(), userMessage);

    final String aiResponse = aiService.chat(telegramId, contextualPayload);

    log.debug("AI conversational engine stream processing finalized successfully.");
    return aiResponse;
  }
}
