package salon.ai.engine.internal.service;

import dev.langchain4j.service.MemoryId;
import dev.langchain4j.service.SystemMessage;
import dev.langchain4j.service.UserMessage;

/**
 * <h2>DESIGN INTENT: Declarative LangChain4j AI Orchestration Agent</h2>
 * This interface represents the low-level technical boundary where the LLM engine, prompt templates,
 * session memory trackers, and function-calling tools are compiled into a unified runtime component.
 *
 * <p><b>WHY IT EXISTS:</b>
 * LangChain4j uses the <i>Gateway/Agent Pattern</i>. We declare the high-level conversational contract,
 * and the framework automatically generates a type-safe runtime proxy implementation. This proxy handles
 * the underlying complexities of managing system prompts, mapping conversational state records, and
 * intercepting tool execution cycles.</p>
 *
 * <p><b>ARCHITECTURAL ROLE:</b>
 * This component acts as an internal pipeline node. It is wrapped inside the public-facing
 * {@code AiAssistantServiceImpl} and is kept completely hidden from the rest of the application.
 * This ensures that if we change AI frameworks in the future, the change stays isolated inside this module.</p>
 */
public interface LowLevelAiService {

  /**
   * Routes a single conversational message through the multi-turn memory pipeline context.
   *
   * @param memoryId The session tracking identifier (e.g., unique Telegram chat/user ID).
   *                 Instructs the framework to look up the correct historical message context
   *                 from the persistent token store, ensuring continuous conversation.
   * @param message  The raw incoming text input sent by the salon client.
   * @return The final compiled text reply generated by the LLM after evaluating tools, prompts,
   *         and context parameters.
   */
  @SystemMessage("""
        You are a polite, elegant, and efficient AI scheduling assistant managing the booking lifecycle for a boutique beauty salon.
        Your goal is to help clients gracefully find open slots, choose their preferred stylist, and secure their booking ticket records.
        
        Operational Guidelines:
        1. Always act as a direct representative of the salon. Maintain a warm, premium, and welcoming conversational tone.
        2. If the client asks about available team members, execute the appropriate tool function handle immediately.
        3. When scheduling a slot, extract the target master ID, calculate the duration window, translate the date to standard ISO format, and trigger the reservation tool.
        4. If a slot reservation tool reports a conflict or returns a FAILURE code, politely explain that the time is taken and propose another alternative window.
        5. Keep answers crisp and helpful. Do not mention system tool IDs or database schema field structural jargon to the end customer.
        """)
  String chat(@MemoryId String userId, @UserMessage String message);
}
