/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.6.1/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

gradle.projectsLoaded {
    rootProject.allprojects {
        group = "av.kabanov"
        version = "1.0.0-SNAPSHOT"
    }
}

rootProject.name = "salon-ai-system"

include("salon-api")
include("salon-db-jooq")
include("salon-ai-engine")
include("salon-app-vaadin")
include("salon-web-http")
include("salon-boot")