-- 1. Masters
-- Мастер уникален по комбинации Имени и Фамилии (например, "Елена Петрова").
CREATE TABLE masters
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name     VARCHAR(50)          NOT NULL,
    last_name      VARCHAR(50)          NOT NULL,
    specialization VARCHAR(255),
    is_active      BOOLEAN DEFAULT TRUE NOT NULL,

    -- NATURAL KEY CONSTRAINT
    CONSTRAINT uk_master_full_name UNIQUE (first_name, last_name)
);

-- 2. Clients
-- Имя обязательно, фамилия может быть пустой (так как из Telegram бот часто может вытащить только имя).
CREATE TABLE clients
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    VARCHAR(50)                         NOT NULL,
    last_name     VARCHAR(50),
    phone         VARCHAR(20),
    telegram_id   VARCHAR(50),
    instagram_id  VARCHAR(50),
    bonus_balance INT       DEFAULT 0                 NOT NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    -- NATURAL KEY CONSTRAINTS
    CONSTRAINT uk_client_phone UNIQUE (phone),
    CONSTRAINT uk_client_telegram UNIQUE (telegram_id),
    CONSTRAINT uk_client_instagram UNIQUE (instagram_id)
);

-- 3. Appointments
-- A master cannot be in two places at once.
-- A master can only have ONE appointment starting at any specific timestamp.
CREATE TABLE appointments
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id        BIGINT                                NOT NULL REFERENCES clients (id) ON DELETE RESTRICT,
    master_id        BIGINT                                NOT NULL REFERENCES masters (id) ON DELETE RESTRICT,
    appointment_time TIMESTAMP                             NOT NULL,
    duration_minutes INT         DEFAULT 60                NOT NULL,
    status           VARCHAR(30) DEFAULT 'AI_PENDING'      NOT NULL,
    price            NUMERIC(10, 2),
    created_at       TIMESTAMP   DEFAULT CURRENT_TIMESTAMP NOT NULL,

    -- BUSINESS INTEGRITY CONSTRAINT (Natural Key for a slot)
    -- Prevents double-booking the same master at the exact same start time
    CONSTRAINT uk_master_time_slot UNIQUE (master_id, appointment_time)
);

-- 4. AI Chat Sessions
-- Handled by the unique_messenger_chat constraint we established earlier.
CREATE TABLE ai_chat_sessions
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    messenger_type VARCHAR(20)                         NOT NULL,
    chat_id        VARCHAR(100)                        NOT NULL,
    is_ai_active   BOOLEAN   DEFAULT TRUE              NOT NULL,
    updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,

    CONSTRAINT unique_messenger_chat UNIQUE (messenger_type, chat_id)
);

-- 5. AI Chat History
CREATE TABLE ai_chat_messages
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT                              NOT NULL REFERENCES ai_chat_sessions (id) ON DELETE CASCADE,
    role       VARCHAR(20)                         NOT NULL,
    content    TEXT                                NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
