/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("buildlogic.java-common-conventions")

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
}

//tasks.test {
//    outputs.upToDateWhen { false }
//}

tasks {
    withType<Test>().configureEach {
        // FIX: Resolves the dynamic inline-mock-maker deprecation warning on JDK 21+
        val mockitoAgent = configurations.testCompileClasspath.get()
            .find { it.name.startsWith("mockito-core-") }

        if (mockitoAgent != null) {
            jvmArgs("-javaagent:${mockitoAgent.absolutePath}")
        }
    }

    test {
        // Отключает кэширование только для базовой задачи test
        outputs.upToDateWhen { false }
    }
}
